## Numpy

I'm following the course at https://www.hackerearth.com/practice/machine-learning/data-manipulation-visualisation-r-python/tutorial-data-manipulation-numpy-pandas-python/tutorial/

In [1]:
import numpy as np
np.__version__

'1.25.0'

In [4]:
#create a list comprising numbers from 0 to 9
L = list(range(10))

In [9]:
#converting integers to string - this style of handling lists is known as list comprehension.
#List comprehension offers a versatile way to handle list manipulations tasks easily. We'll learn about them in future tutorials. Here's an example.  

print([str(c) for c in L])

[type(item) for item in L]

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


[int, int, int, int, int, int, int, int, int, int]

In [32]:
#creating arrays
np.zeros(10, dtype='int')

#creating a 3 row x 5 column matrix
np.ones((3,5), dtype=float)

#creating a matrix with a predefined value
np.full((3,5), 1.23)

#create an array with a set sequence
np.arange(0, 20, 2)

#create an array of even space between the given range of values
np.linspace(0, 1, 5)

#create a 3x3 array with mean 0 and standard deviation 1 in a given dimension
np.random.normal(0, 1, (3,3))

#create an identity matrix
np.eye(3)

#set a random seed
np.random.seed(0)

x1 = np.random.randint(10, size=6) #one dimension
x2 = np.random.randint(10, size=(3,4)) #two dimension
x3 = np.random.randint(10, size=(3,4,5)) #three dimension


print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
('x3 ndim:', 3)
('x3 shape:', (3, 4, 5))
('x3 size: ', 60)

x3 ndim: 3
x3 shape: (3, 4, 5)
x3 size:  60


array([[8, 1, 5, 9, 8],
       [9, 4, 3, 0, 3],
       [5, 0, 2, 3, 8],
       [1, 3, 3, 3, 7]])

In [35]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [38]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
print(np.vstack([x,grid]))

#Similarly, you can add an array using np.hstack
z = np.array([[9],[9]])
print(np.hstack([grid,z]))

[[ 3  4  5]
 [ 1  2  3]
 [17 18 19]]
[[ 1  2  3  9]
 [17 18 19  9]]


In [42]:
x = np.arange(10)
x


x1,x2,x3 = np.split(x,[3,6])
print (x1,x2,x3)

grid = np.arange(16).reshape((4,4))
grid
upper,lower = np.vsplit(grid,[2])
print (upper, lower)

[0 1 2] [3 4 5] [6 7 8 9]
[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]
